/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payment;

import Login.Login;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.tools.ShellFunctions.input;

/**
 *
 * @author User
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        getContentPane().setBackground(Color.blue);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPatientID = new javax.swing.JLabel();
        jLabelPatientName = new javax.swing.JLabel();
        jLabelPaymentMethod = new javax.swing.JLabel();
        jLabelBillReceivedOn = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelTotalAmount = new javax.swing.JLabel();
        jLabelDueDate = new javax.swing.JLabel();
        jLabelPaidBy = new javax.swing.JLabel();
        jLabelPaymentDate = new javax.swing.JLabel();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtDescription = new javax.swing.JTextField();
        jtxtBillReceivedOn = new javax.swing.JTextField();
        jtxtDueDate = new javax.swing.JTextField();
        jtxtTotalAmount = new javax.swing.JTextField();
        jtxtPaidBy = new javax.swing.JTextField();
        jtxtPaymentDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcmbPaymentMethod = new javax.swing.JComboBox<>();
        jbtnUpdate = new javax.swing.JButton();
        jbtnNew = new javax.swing.JButton();
        jbtnCalculate = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jbtnLoad = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jLabelTotalAmountReceived = new javax.swing.JLabel();
        jtxtTotalAmountReceived = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPatientID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPatientID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPatientID.setText("Patient ID:");

        jLabelPatientName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPatientName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPatientName.setText("Patient Name:");

        jLabelPaymentMethod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPaymentMethod.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPaymentMethod.setText("Payment Method:");

        jLabelBillReceivedOn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBillReceivedOn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBillReceivedOn.setText("Bill Recieved On:");

        jLabelDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription.setText("Description:");

        jLabelTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotalAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalAmount.setText("Amount (RM):");

        jLabelDueDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDueDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDueDate.setText("Due Date:");

        jLabelPaidBy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPaidBy.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPaidBy.setText("Paid by:");

        jLabelPaymentDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPaymentDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPaymentDate.setText("Payment Date:");

        jTable1.setBackground(new java.awt.Color(51, 51, 255));
        jTable1.setForeground(new java.awt.Color(255, 255, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name", "Payment Method", "Description", "Bill Received On", "Due Date", "Amount (RM)", "Paid by", "Payment Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jcmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit/Credit Card", "Cheque" }));

        jbtnUpdate.setBackground(new java.awt.Color(51, 255, 51));
        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnNew.setBackground(new java.awt.Color(51, 255, 51));
        jbtnNew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnNew.setText("New");
        jbtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewActionPerformed(evt);
            }
        });

        jbtnCalculate.setBackground(new java.awt.Color(51, 255, 51));
        jbtnCalculate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCalculate.setText("Calculate");
        jbtnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalculateActionPerformed(evt);
            }
        });

        jbtnSave.setBackground(new java.awt.Color(51, 255, 51));
        jbtnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnLoad.setBackground(new java.awt.Color(51, 255, 51));
        jbtnLoad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLoad.setText("Load");
        jbtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoadActionPerformed(evt);
            }
        });

        jbtnDelete.setBackground(new java.awt.Color(51, 255, 51));
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnExit.setBackground(new java.awt.Color(51, 255, 51));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jLabelTotalAmountReceived.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTotalAmountReceived.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalAmountReceived.setText("Total Amount Received:");

        jtxtTotalAmountReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalAmountReceivedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelBillReceivedOn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPaymentMethod, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabelDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelPaymentDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelPaidBy, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtPaidBy)
                            .addComponent(jtxtTotalAmount)
                            .addComponent(jtxtDescription)
                            .addComponent(jtxtPatientName)
                            .addComponent(jtxtPatientID)
                            .addComponent(jtxtDueDate)
                            .addComponent(jtxtBillReceivedOn)
                            .addComponent(jtxtPaymentDate)
                            .addComponent(jcmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(jLabelTotalAmountReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtTotalAmountReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelPatientID)
                                            .addComponent(jtxtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnUpdate))
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtxtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnNew)
                                        .addComponent(jLabelPatientName)))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTotalAmountReceived)
                                    .addComponent(jtxtTotalAmountReceived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPaymentMethod)
                            .addComponent(jbtnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDescription)
                            .addComponent(jbtnCalculate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDueDate))
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtBillReceivedOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBillReceivedOn)
                                    .addComponent(jbtnSave))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnLoad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnExit)
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotalAmount))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtPaidBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPaidBy)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPaymentDate)
                    .addComponent(jtxtPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
         model.addRow(new Object []{
         jtxtPatientID.getText(),
         jtxtPatientName.getText(),
         jcmbPaymentMethod.getSelectedItem().toString(),
         jtxtDescription.getText(),
         jtxtBillReceivedOn.getText(),
         jtxtDueDate.getText(),
         jtxtTotalAmount.getText(),
         jtxtPaidBy.getText(),
         jtxtPaymentDate.getText(),           
       
    });                        
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow() ==-1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No data to delete",
                        "Pharmarcy Inventory System Managament", JOptionPane.OK_OPTION);
            }else{
                JOptionPane.showMessageDialog(null, "Select a row to delete",
                        "Pharmarcy Inventory System Management", JOptionPane.OK_OPTION);
            }
        }else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewActionPerformed
        // TODO add your handling code here:
         jtxtPatientID.setText("");
         jtxtPatientName.setText("");
         jtxtDescription.setText("");
         jtxtBillReceivedOn.setText("");
         jtxtDueDate.setText("");
         jtxtTotalAmount.setText("");
         jtxtPaidBy.setText("");
         jtxtPaymentDate.setText("");    
        
    }//GEN-LAST:event_jbtnNewActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {         
            String name = JOptionPane.showInputDialog(frame, "Please specify the file path to save your table:");
            File file = new File(name); 
            if(!file.exists()){
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i = 0; i<jTable1.getRowCount(); i++){
                for(int j = 0; j<jTable1.getColumnCount(); j++){
                    bw.write(jTable1.getModel().getValueAt(i,j)+"# ");
                    
                }
                
                bw.newLine();
                
            }
            
            bw.close();
            fw.close();
            model.setRowCount(0);
            jtxtPatientID.setText("");
            jtxtPatientName.setText("");
            jtxtDescription.setText("");
            jtxtBillReceivedOn.setText("");
            jtxtDueDate.setText("");
            jtxtTotalAmount.setText("");
            jtxtPaidBy.setText("");
            jtxtPaymentDate.setText("");
            
            JOptionPane.showMessageDialog(null,"Saved!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"FILE not created! C:\\Users\\User\\Desktop\\Pharmarcy\\Payment.txt not found");
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoadActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        FileReader fr = null;
        try {
            String name = JOptionPane.showInputDialog(frame, "Please specify the file path to load your table:");
            File file = new File(name);
            fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
           
            Object[] lines = br.lines().toArray();
            for(int i=0;i<lines.length;i++){
                String [] row = lines[i].toString().split("# ");
                model.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnLoadActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit Payment Record","Pharmacy Management System",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            Login page = new Login();
            page.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtxtTotalAmountReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalAmountReceivedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalAmountReceivedActionPerformed

    private void jbtnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalculateActionPerformed
        // TODO add your handling code here:
        double total =0;
        DecimalFormat df2 = new DecimalFormat(".##");
        for(int i=0;i<jTable1.getRowCount(); i++){
            total = total +Double.parseDouble(jTable1.getValueAt(i,6).toString());
          
           
         }        
        String input = df2.format(total);
        jtxtTotalAmountReceived.setText(input);
        
    }//GEN-LAST:event_jbtnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBillReceivedOn;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelDueDate;
    private javax.swing.JLabel jLabelPaidBy;
    private javax.swing.JLabel jLabelPatientID;
    private javax.swing.JLabel jLabelPatientName;
    private javax.swing.JLabel jLabelPaymentDate;
    private javax.swing.JLabel jLabelPaymentMethod;
    private javax.swing.JLabel jLabelTotalAmount;
    private javax.swing.JLabel jLabelTotalAmountReceived;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnCalculate;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLoad;
    private javax.swing.JButton jbtnNew;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcmbPaymentMethod;
    private javax.swing.JTextField jtxtBillReceivedOn;
    private javax.swing.JTextField jtxtDescription;
    private javax.swing.JTextField jtxtDueDate;
    private javax.swing.JTextField jtxtPaidBy;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtPaymentDate;
    private javax.swing.JTextField jtxtTotalAmount;
    private javax.swing.JTextField jtxtTotalAmountReceived;
    // End of variables declaration//GEN-END:variables
}
