/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import Login.Login;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author User
 */

public class Pharmacy extends javax.swing.JFrame {

    /**
     * Creates new form Pharmacy
     */
    public Pharmacy() {
        initComponents();
        getContentPane().setBackground(Color.blue);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelReferenceNo = new javax.swing.JLabel();
        jtxtRef = new javax.swing.JTextField();
        javax.swing.JLabel jlabelNameOfTablets = new javax.swing.JLabel();
        jlabelDose = new javax.swing.JLabel();
        jtxtDose = new javax.swing.JTextField();
        jlabelNumberOfTablets = new javax.swing.JLabel();
        jtxtNumberTablets = new javax.swing.JTextField();
        jlabelIssuedDate = new javax.swing.JLabel();
        jtxtIssuedDate = new javax.swing.JTextField();
        jlabelExpDate = new javax.swing.JLabel();
        jtxtExpDate = new javax.swing.JTextField();
        jlabelPossibleSideEffects = new javax.swing.JLabel();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jlabelAdmin = new javax.swing.JLabel();
        jlabelStorageAdvice = new javax.swing.JLabel();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jlabelHowToUseMedication = new javax.swing.JLabel();
        jtxtHowToUseMedication = new javax.swing.JTextField();
        jlabelQuantity = new javax.swing.JLabel();
        jtxtQuantity = new javax.swing.JTextField();
        jlabelPrice = new javax.swing.JLabel();
        jtxtPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbtnUpdateActionPerformed = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnLoad = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbnExit = new javax.swing.JButton();
        jbtnNew = new javax.swing.JButton();
        jtxtNameOfTablets = new javax.swing.JTextField();
        jcmbAdmin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelReferenceNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelReferenceNo.setForeground(new java.awt.Color(255, 255, 255));
        jlabelReferenceNo.setText("Reference No.:");
        getContentPane().add(jlabelReferenceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 30));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRefActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 240, -1));

        jlabelNameOfTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelNameOfTablets.setForeground(new java.awt.Color(255, 255, 255));
        jlabelNameOfTablets.setText("Name of Tablets:");
        getContentPane().add(jlabelNameOfTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 30));

        jlabelDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelDose.setForeground(new java.awt.Color(255, 255, 255));
        jlabelDose.setText("Dose (mg):");
        getContentPane().add(jlabelDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 30));

        jtxtDose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDoseActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 240, -1));

        jlabelNumberOfTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelNumberOfTablets.setForeground(new java.awt.Color(255, 255, 255));
        jlabelNumberOfTablets.setText("Number of Tablets:");
        getContentPane().add(jlabelNumberOfTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 30));

        jtxtNumberTablets.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtNumberTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumberTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 240, -1));

        jlabelIssuedDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelIssuedDate.setForeground(new java.awt.Color(255, 255, 255));
        jlabelIssuedDate.setText("Issued Date:");
        getContentPane().add(jlabelIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        jtxtIssuedDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtIssuedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIssuedDateActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 240, -1));

        jlabelExpDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelExpDate.setForeground(new java.awt.Color(255, 255, 255));
        jlabelExpDate.setText("Expiry Date:");
        jlabelExpDate.setToolTipText("");
        getContentPane().add(jlabelExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 30));

        jtxtExpDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtExpDateActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 240, -1));

        jlabelPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelPossibleSideEffects.setForeground(new java.awt.Color(255, 255, 255));
        jlabelPossibleSideEffects.setText("Possible Side Effects:");
        getContentPane().add(jlabelPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, 30));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtPossibleSideEffects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPossibleSideEffectsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, 240, -1));

        jlabelAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jlabelAdmin.setText("Admin:");
        getContentPane().add(jlabelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, 30));

        jlabelStorageAdvice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelStorageAdvice.setForeground(new java.awt.Color(255, 255, 255));
        jlabelStorageAdvice.setText("Storage Advice:");
        getContentPane().add(jlabelStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, 30));

        jtxtStorageAdvice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtStorageAdvice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStorageAdviceActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 240, -1));

        jlabelHowToUseMedication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelHowToUseMedication.setForeground(new java.awt.Color(255, 255, 255));
        jlabelHowToUseMedication.setText("How to Use Medication:");
        getContentPane().add(jlabelHowToUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, 40));

        jtxtHowToUseMedication.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtHowToUseMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHowToUseMedicationActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtHowToUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 240, -1));

        jlabelQuantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jlabelQuantity.setText("Quantity in Storage:");
        getContentPane().add(jlabelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 200, 30));

        jtxtQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 70, 30));

        jlabelPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelPrice.setForeground(new java.awt.Color(255, 255, 255));
        jlabelPrice.setText("Price(RM):");
        jlabelPrice.setToolTipText("");
        getContentPane().add(jlabelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 130, 20));

        jtxtPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPriceActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 110, -1));

        jTable1.setBackground(new java.awt.Color(102, 102, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setForeground(new java.awt.Color(255, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets", "Refertence No.", "Dose(mg)", "Number of Tablets", "Issued Date", "Exp Date", "Possible Side Effects", "Admin", "Storage Advice", "How to use Medication", "Quantity", "Price(RM)"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 0, 153));
        jTable1.setPreferredSize(new java.awt.Dimension(900, 900));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 51));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1270, 240));

        jPanel1.setBackground(new java.awt.Color(46, 0, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnUpdateActionPerformed.setBackground(new java.awt.Color(102, 255, 102));
        jbtnUpdateActionPerformed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnUpdateActionPerformed.setText("Update");
        jbtnUpdateActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformedActionPerformed(evt);
            }
        });

        jbtnDelete.setBackground(new java.awt.Color(102, 255, 102));
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnLoad.setBackground(new java.awt.Color(102, 255, 102));
        jbtnLoad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnLoad.setText("Load");
        jbtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoadActionPerformed(evt);
            }
        });

        jbtnSave.setBackground(new java.awt.Color(102, 255, 102));
        jbtnSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnLogin.setBackground(new java.awt.Color(102, 255, 102));
        jbtnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jbnExit.setBackground(new java.awt.Color(102, 255, 102));
        jbnExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbnExit.setText("Exit");
        jbnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnExitActionPerformed(evt);
            }
        });

        jbtnNew.setBackground(new java.awt.Color(102, 255, 102));
        jbtnNew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnNew.setText("New");
        jbtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jbtnUpdateActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jbtnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jbtnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jbnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnUpdateActionPerformed)
                    .addComponent(jbtnLoad)
                    .addComponent(jbtnSave)
                    .addComponent(jbtnLogin)
                    .addComponent(jbnExit)
                    .addComponent(jbtnNew)
                    .addComponent(jbtnDelete))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1260, 60));

        jtxtNameOfTablets.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtNameOfTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameOfTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNameOfTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 240, -1));

        jcmbAdmin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcmbAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Harry", "Dennis", "KehHX", "NgSY" }));
        jcmbAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRefActionPerformed

    private void jtxtDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDoseActionPerformed

    private void jtxtNumberTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumberTabletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumberTabletsActionPerformed

    private void jtxtIssuedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIssuedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIssuedDateActionPerformed

    private void jtxtExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtExpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtExpDateActionPerformed

    private void jtxtPossibleSideEffectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPossibleSideEffectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPossibleSideEffectsActionPerformed

    private void jtxtStorageAdviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStorageAdviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStorageAdviceActionPerformed

    private void jtxtHowToUseMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHowToUseMedicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHowToUseMedicationActionPerformed

    private void jtxtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQuantityActionPerformed

    private void jtxtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPriceActionPerformed

    private void jbtnUpdateActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformedActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
         model.addRow(new Object []{
         jtxtNameOfTablets.getText(),
         jtxtRef.getText(),
         jtxtDose.getText(),
         jtxtNumberTablets.getText(),
         jtxtIssuedDate.getText(),
         jtxtExpDate.getText(),
         jtxtPossibleSideEffects.getText(),
         jcmbAdmin.getSelectedItem().toString(),
         jtxtStorageAdvice.getText(),
         jtxtHowToUseMedication.getText(),
         jtxtQuantity.getText(),
         jtxtPrice.getText(),});
      
       
    }//GEN-LAST:event_jbtnUpdateActionPerformedActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow() ==-1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No data to delete",
                        "Pharmarcy Inventory System Managament", JOptionPane.OK_OPTION);
            }else{
                JOptionPane.showMessageDialog(null, "Select a row to delete",
                        "Pharmarcy Inventory System Management", JOptionPane.OK_OPTION);
            }
        }else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed
private JFrame frame;
    private void jbnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnExitActionPerformed
         frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit Pharmacy Inventory Management System","Pharmacy Inventory Management System",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            Login page = new Login();
            page.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jbnExitActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jtxtNameOfTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameOfTabletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameOfTabletsActionPerformed

    private void jbtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewActionPerformed
        // TODO add your handling code here:
         jtxtNameOfTablets.setText("");
         jtxtRef.setText("");
         jtxtDose.setText("");
         jtxtNumberTablets.setText("");
         jtxtIssuedDate.setText("");
         jtxtExpDate.setText("");
         jtxtPossibleSideEffects.setText("");
         jtxtStorageAdvice.setText("");
         jtxtHowToUseMedication.setText("");
         jtxtQuantity.setText("");
         jtxtPrice.setText("");
    }//GEN-LAST:event_jbtnNewActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            String name = JOptionPane.showInputDialog(frame, "Please specify the file path to save your table:");
            File file = new File(name);
            if(!file.exists()){
                file.createNewFile();
            }
            
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            
            BufferedWriter bw = new BufferedWriter(fw);
            for(int i = 0; i<jTable1.getRowCount(); i++){
                for(int j = 0; j<jTable1.getColumnCount(); j++){
                    bw.write(jTable1.getModel().getValueAt(i,j)+"# ");
                    
                }
                
                bw.newLine();
                
            }
            
            bw.close();
            fw.close();
            model.setRowCount(0);
         jtxtNameOfTablets.setText("");
         jtxtRef.setText("");
         jtxtDose.setText("");
         jtxtNumberTablets.setText("");
         jtxtIssuedDate.setText("");
         jtxtExpDate.setText("");
         jtxtPossibleSideEffects.setText("");
         jtxtStorageAdvice.setText("");
         jtxtHowToUseMedication.setText("");
         jtxtQuantity.setText("");
         jtxtPrice.setText("");
            JOptionPane.showMessageDialog(null,"Saved!");
        } catch (IOException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jcmbAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbAdminActionPerformed

    private void jbtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoadActionPerformed
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       model.setRowCount(0);
        FileReader fr = null;
        try {
            
            String name = JOptionPane.showInputDialog(frame, "Please specify the file path to load your table:");
            File file = new File(name);
            fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            Object[] lines = br.lines().toArray();
            for(int i=0;i<lines.length;i++){
                String [] row = lines[i].toString().split("# ");
                model.addRow(row);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         
         
    }//GEN-LAST:event_jbtnLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pharmacy().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbnExit;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnLoad;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnNew;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnUpdateActionPerformed;
    private javax.swing.JComboBox<String> jcmbAdmin;
    private javax.swing.JLabel jlabelAdmin;
    private javax.swing.JLabel jlabelDose;
    private javax.swing.JLabel jlabelExpDate;
    private javax.swing.JLabel jlabelHowToUseMedication;
    private javax.swing.JLabel jlabelIssuedDate;
    private javax.swing.JLabel jlabelNumberOfTablets;
    private javax.swing.JLabel jlabelPossibleSideEffects;
    private javax.swing.JLabel jlabelPrice;
    private javax.swing.JLabel jlabelQuantity;
    private javax.swing.JLabel jlabelReferenceNo;
    private javax.swing.JLabel jlabelStorageAdvice;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtHowToUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtNameOfTablets;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextField jtxtPrice;
    private javax.swing.JTextField jtxtQuantity;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
